Feature/milestone 02
carlosveigadev/react-calculator pull request #2
Opened 2021-02-25 23:48 UTC by carlosveigadev

- Add main files and separate the components folder;
- Add App, Display, ButtonPanel, and Button content;
- Add Default values for some elements;
- Add type requirements for props.

2021-02-26 06:06 UTC, wathigo requested changes
## CHANGES REQUIRED :o: 
Great job on this project.
Let's fix one issue before we proceed to the next milestone. see the comment :point_down: 

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

2021-02-26 06:06 UTC, wathigo commented on src/components/App.js
> +);
Has children components wrapped in React.Fragment short syntax ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png))

2021-02-26 12:37 UTC, carlosveigadev commented
Hi @wathigo, thanks for the review.
I implemented the improvements as suggested.

2021-02-27 02:12 UTC, trekab approved these changes
#### Approved! :tada: 
Well done @carlosveigadev! You may proceed to your next milestone.

__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2021-02-27 02:37 UTC, merged